# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='scheduler_status.proto',
  package='',
  serialized_pb='\n\x16scheduler_status.proto\"\"\n\rStatusRequest\x12\x11\n\tverbosity\x18\x01 \x01(\x05\"\"\n\x0eStatusResponse\x12\x10\n\x08jobCount\x18\x01 \x01(\x05\x32:\n\rStatusService\x12)\n\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponseB\x03\x90\x01\x01')




_STATUSREQUEST = descriptor.Descriptor(
  name='StatusRequest',
  full_name='StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='verbosity', full_name='StatusRequest.verbosity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=60,
)


_STATUSRESPONSE = descriptor.Descriptor(
  name='StatusResponse',
  full_name='StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='jobCount', full_name='StatusResponse.jobCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE

class StatusRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUSREQUEST
  
  # @@protoc_insertion_point(class_scope:StatusRequest)

class StatusResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUSRESPONSE
  
  # @@protoc_insertion_point(class_scope:StatusResponse)


_STATUSSERVICE = descriptor.ServiceDescriptor(
  name='StatusService',
  full_name='StatusService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=98,
  serialized_end=156,
  methods=[
  descriptor.MethodDescriptor(
    name='Status',
    full_name='StatusService.Status',
    index=0,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
])

class StatusService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _STATUSSERVICE
class StatusService_Stub(StatusService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _STATUSSERVICE

# @@protoc_insertion_point(module_scope)
